name: groupscholar_mentor_matchmap
description: Mentor matching and coverage CLI for Group Scholar.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.9

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  path: ^1.9.0
  postgres: ^3.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
